/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorldRouteImport } from './routes/world'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PlayerRouteImport } from './routes/player'
import { Route as NearbyRouteImport } from './routes/nearby'
import { Route as AreaRouteImport } from './routes/area'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArticleIdRouteImport } from './routes/article.$id'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiNewsWorldRouteImport } from './routes/api/news.world'
import { Route as ApiNewsValidateFeedRouteImport } from './routes/api/news.validate-feed'
import { Route as ApiNewsSummarizeRouteImport } from './routes/api/news.summarize'
import { Route as ApiNewsMunicipalRouteImport } from './routes/api/news.municipal'
import { Route as ApiNewsLocalRouteImport } from './routes/api/news.local'

const WorldRoute = WorldRouteImport.update({
  id: '/world',
  path: '/world',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerRoute = PlayerRouteImport.update({
  id: '/player',
  path: '/player',
  getParentRoute: () => rootRouteImport,
} as any)
const NearbyRoute = NearbyRouteImport.update({
  id: '/nearby',
  path: '/nearby',
  getParentRoute: () => rootRouteImport,
} as any)
const AreaRoute = AreaRouteImport.update({
  id: '/area',
  path: '/area',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleIdRoute = ArticleIdRouteImport.update({
  id: '/article/$id',
  path: '/article/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsWorldRoute = ApiNewsWorldRouteImport.update({
  id: '/api/news/world',
  path: '/api/news/world',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsValidateFeedRoute = ApiNewsValidateFeedRouteImport.update({
  id: '/api/news/validate-feed',
  path: '/api/news/validate-feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsSummarizeRoute = ApiNewsSummarizeRouteImport.update({
  id: '/api/news/summarize',
  path: '/api/news/summarize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsMunicipalRoute = ApiNewsMunicipalRouteImport.update({
  id: '/api/news/municipal',
  path: '/api/news/municipal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsLocalRoute = ApiNewsLocalRouteImport.update({
  id: '/api/news/local',
  path: '/api/news/local',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/area': typeof AreaRoute
  '/nearby': typeof NearbyRoute
  '/player': typeof PlayerRoute
  '/settings': typeof SettingsRoute
  '/welcome': typeof WelcomeRoute
  '/world': typeof WorldRoute
  '/api/tts': typeof ApiTtsRoute
  '/article/$id': typeof ArticleIdRoute
  '/api/news/local': typeof ApiNewsLocalRoute
  '/api/news/municipal': typeof ApiNewsMunicipalRoute
  '/api/news/summarize': typeof ApiNewsSummarizeRoute
  '/api/news/validate-feed': typeof ApiNewsValidateFeedRoute
  '/api/news/world': typeof ApiNewsWorldRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/area': typeof AreaRoute
  '/nearby': typeof NearbyRoute
  '/player': typeof PlayerRoute
  '/settings': typeof SettingsRoute
  '/welcome': typeof WelcomeRoute
  '/world': typeof WorldRoute
  '/api/tts': typeof ApiTtsRoute
  '/article/$id': typeof ArticleIdRoute
  '/api/news/local': typeof ApiNewsLocalRoute
  '/api/news/municipal': typeof ApiNewsMunicipalRoute
  '/api/news/summarize': typeof ApiNewsSummarizeRoute
  '/api/news/validate-feed': typeof ApiNewsValidateFeedRoute
  '/api/news/world': typeof ApiNewsWorldRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/area': typeof AreaRoute
  '/nearby': typeof NearbyRoute
  '/player': typeof PlayerRoute
  '/settings': typeof SettingsRoute
  '/welcome': typeof WelcomeRoute
  '/world': typeof WorldRoute
  '/api/tts': typeof ApiTtsRoute
  '/article/$id': typeof ArticleIdRoute
  '/api/news/local': typeof ApiNewsLocalRoute
  '/api/news/municipal': typeof ApiNewsMunicipalRoute
  '/api/news/summarize': typeof ApiNewsSummarizeRoute
  '/api/news/validate-feed': typeof ApiNewsValidateFeedRoute
  '/api/news/world': typeof ApiNewsWorldRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/area'
    | '/nearby'
    | '/player'
    | '/settings'
    | '/welcome'
    | '/world'
    | '/api/tts'
    | '/article/$id'
    | '/api/news/local'
    | '/api/news/municipal'
    | '/api/news/summarize'
    | '/api/news/validate-feed'
    | '/api/news/world'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/area'
    | '/nearby'
    | '/player'
    | '/settings'
    | '/welcome'
    | '/world'
    | '/api/tts'
    | '/article/$id'
    | '/api/news/local'
    | '/api/news/municipal'
    | '/api/news/summarize'
    | '/api/news/validate-feed'
    | '/api/news/world'
  id:
    | '__root__'
    | '/'
    | '/area'
    | '/nearby'
    | '/player'
    | '/settings'
    | '/welcome'
    | '/world'
    | '/api/tts'
    | '/article/$id'
    | '/api/news/local'
    | '/api/news/municipal'
    | '/api/news/summarize'
    | '/api/news/validate-feed'
    | '/api/news/world'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AreaRoute: typeof AreaRoute
  NearbyRoute: typeof NearbyRoute
  PlayerRoute: typeof PlayerRoute
  SettingsRoute: typeof SettingsRoute
  WelcomeRoute: typeof WelcomeRoute
  WorldRoute: typeof WorldRoute
  ApiTtsRoute: typeof ApiTtsRoute
  ArticleIdRoute: typeof ArticleIdRoute
  ApiNewsLocalRoute: typeof ApiNewsLocalRoute
  ApiNewsMunicipalRoute: typeof ApiNewsMunicipalRoute
  ApiNewsSummarizeRoute: typeof ApiNewsSummarizeRoute
  ApiNewsValidateFeedRoute: typeof ApiNewsValidateFeedRoute
  ApiNewsWorldRoute: typeof ApiNewsWorldRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/world': {
      id: '/world'
      path: '/world'
      fullPath: '/world'
      preLoaderRoute: typeof WorldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player': {
      id: '/player'
      path: '/player'
      fullPath: '/player'
      preLoaderRoute: typeof PlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nearby': {
      id: '/nearby'
      path: '/nearby'
      fullPath: '/nearby'
      preLoaderRoute: typeof NearbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/area': {
      id: '/area'
      path: '/area'
      fullPath: '/area'
      preLoaderRoute: typeof AreaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$id': {
      id: '/article/$id'
      path: '/article/$id'
      fullPath: '/article/$id'
      preLoaderRoute: typeof ArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/news/world': {
      id: '/api/news/world'
      path: '/api/news/world'
      fullPath: '/api/news/world'
      preLoaderRoute: typeof ApiNewsWorldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/news/validate-feed': {
      id: '/api/news/validate-feed'
      path: '/api/news/validate-feed'
      fullPath: '/api/news/validate-feed'
      preLoaderRoute: typeof ApiNewsValidateFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/news/summarize': {
      id: '/api/news/summarize'
      path: '/api/news/summarize'
      fullPath: '/api/news/summarize'
      preLoaderRoute: typeof ApiNewsSummarizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/news/municipal': {
      id: '/api/news/municipal'
      path: '/api/news/municipal'
      fullPath: '/api/news/municipal'
      preLoaderRoute: typeof ApiNewsMunicipalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/news/local': {
      id: '/api/news/local'
      path: '/api/news/local'
      fullPath: '/api/news/local'
      preLoaderRoute: typeof ApiNewsLocalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AreaRoute: AreaRoute,
  NearbyRoute: NearbyRoute,
  PlayerRoute: PlayerRoute,
  SettingsRoute: SettingsRoute,
  WelcomeRoute: WelcomeRoute,
  WorldRoute: WorldRoute,
  ApiTtsRoute: ApiTtsRoute,
  ArticleIdRoute: ArticleIdRoute,
  ApiNewsLocalRoute: ApiNewsLocalRoute,
  ApiNewsMunicipalRoute: ApiNewsMunicipalRoute,
  ApiNewsSummarizeRoute: ApiNewsSummarizeRoute,
  ApiNewsValidateFeedRoute: ApiNewsValidateFeedRoute,
  ApiNewsWorldRoute: ApiNewsWorldRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
